language: node_js
node_js:
    - "12"
dist: trusty
service:
    - mongodb
    - redis-server
env:
    - NODE_ENV=ci PORT=3000
cache:
    directories:
        - node_modules
install:
    - yarn
    - npm run build
script:
    - nohup npm run start &
    - sleep 3
    - npm run test

